<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 11/5/2020
 * Time: 10:44 PM
 */

use App\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $project = Project::create([
            'name' => 'admin',
            'distance'=>10.5,
            'gps_x'=>21.0158321,
            'gps_y'=>25.10526354,
            'percentage1'=>100,
            'percentage2'=>50,
            'percentage3'=>0,
            'description' => "The project is the first project and is generated by bot"
        ]);

        $project->teams->sync([0]);
    }
}
